FROM scratch AS rpms

COPY rpms/* /rpms/

# Change this to your current image!
FROM quay.io/fedora-ostree-desktops/kinoite:41

# Example of how to install all RPMs from the rpms folder.
RUN --mount=type=bind,from=rpms,source=/rpms,target=/rpms \
    --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    dnf5 install -y --setopt=keepcache=1 /rpms/*

# Clean var folder to pass linting checks.
RUN rm -rf /var/* && ostree container commit

RUN bootc container lint
