FROM ghcr.io/ublue-os/kinoite-nvidia:41

# Example of installing steam, VR tools, and other gaming adjacent packages
# Also includes example of how to remove Firefox if you use the flatpak
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    dnf5 remove -y --setopt=keepcache=1 \
        firefox firefox-langpacks && \
    dnf5 install -y --setopt=keepcache=1 \
        steam steam-devices \
        monado-vulkan-layers \
        input-remapper \
        libi2c-devel lm_sensors \
        zsh && \
    systemctl enable input-remapper

# Example of how to use custom COPR repositories, then disable them so later RUN commands do not use them
# This installs the wallpaper-engine-kde-plugin and patched gamescope
RUN --mount=type=cache,dst=/var/cache \
    --mount=type=cache,dst=/var/log \
    --mount=type=tmpfs,dst=/tmp \
    REPOS="kylegospo/bazzite-multilib kylegospo/wallpaper-engine-kde-plugin"; \
    for repo in $REPOS; do dnf5 -y copr enable $repo && dnf5 -y config-manager setopt "*${repo////:}.priority=10"; done && \
    dnf5 install -y --setopt=keepcache=1 \
        wallpaper-engine-kde-plugin \
        gamescope && \
    for repo in $REPOS; do dnf5 -y copr disable $repo; done

# Clean var folder to pass linting checks.
RUN rm -rf /var/* && ostree container commit

RUN bootc container lint
